### PR TITLE
version 1.3.0

### PR DESCRIPTION
**Pull request by Laserlicht**

### CODE REVIEW

**Comment by Laserlicht** [comment]
@Alexander-Wilms Can you merge? We have a new release. :)

**Comment by Alexander-Wilms** [comment]
Yes, I'll test it and then merge.

**Comment by Alexander-Wilms** [comment]
Btw, the modules in the Flatpak manifest get updated automatically, I think it might take a few hours at most for a new version to appear here: https://release-monitoring.org/project/5456/

**Comment by Laserlicht** [comment]
Yes, I know. But the patch had to be removed anyway and the build didn't work right away either. :)

**Pull request merged**
