### PR TITLE
Update SDK to version 6.6

### PR DESCRIPTION
**Pull request by Alexander-Wilms**

### CODE REVIEW

**Comment by Alexander-Wilms** [comment]
blocked until the next vcmi release

**Comment by Alexander-Wilms** [comment]
Looks like https://github.com/flathub/eu.vcmi.VCMI/issues/108 returned

**Comment by Alexander-Wilms** [comment]
bot, build

**Comment by Justinzobel** [comment]
Maybe use the ffmpeg extension from FreeDesktop to save you building ffmpeg (and it's current failure): https://github.com/flathub/org.remmina.Remmina/blob/e4f5f5e1e7bf07ef1cf2e15ae23952c248beeac7/org.remmina.Remmina.json#L49 for example.

**Comment by Alexander-Wilms** [comment]
@Justinzobel Tanks for the hint.

Could you try the build and test if the intro videos and the video after a battle still work?

**Comment by Justinzobel** [comment]
I've never used this Flatpak, I was just going around and trying to get Flatpaks off of the EOL runtime. I suppose I can install and try it.

**Comment by Justinzobel** [comment]
I just installed and tried it, but it needs some game data that I don't have.

**Comment by Alexander-Wilms** [comment]
Alright, I'll be able to test it in a few days.

Or could you test it, @Laserlicht ?

**Comment by Laserlicht** [comment]
@Alexander-Wilms Yes it's working. :)

@Justinzobel It was not possible to use in the past. Because BIK and SMK support was missing. But they reworked 23.08, so that it is possible now. :)

**Comment by Alexander-Wilms** [comment]
Great, thanks!

**Pull request merged**
